server:
  context-path: /lad-admin
  port: 8099
spring:
  data:
    mongodb:
      base:
        database: mongo
        uri: 180.76.138.200:26134
#        uri: 192.168.0.5:26134
        username: apple2
        password: 1u#3WeiMLfg!A&#G1^JcB&sUGatMaa1I
        repositories: true
      infor:
        database: news
        uri: 180.76.138.200:26134
#        uri: 192.168.0.5:26134
        username: apple2
        password: 1u#3WeiMLfg!A&#G1^JcB&sUGatMaa1I
        repositories: true


#  thymeleaf:
#    cache: false
#    check-template-location: true
#    content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    mode: HTML5
#    prefix: classpath:/templates/
#    suffix: .html